CFLAGS = -O3
MFLAGS = -lm
all: 1_hw13.exe 2_hw13.exe 3_hw13.exe 4_hw13.exe 5_hw13.exe 6_hw13.exe 7_hw13.exe 8_hw13.exe 9_hw13.exe 10_hw13.exe

1_hw13.exe: 1_hw13.o hw13.o
	gcc 1_hw13.o hw13.o $(MFLAGS) -o 1_hw13.exe
1_hw13.o: 1_hw13.c hw13.h
	gcc -c $(CFLAGS) 1_hw13.c
hw13.o: hw13.c hw13.h
	gcc -c $(CFLAGS) hw13.c

2_hw13.exe: 2_hw13.o hw13.o
	gcc 2_hw13.o hw13.o $(MFLAGS) -o 2_hw13.exe
2_hw13.o: 2_hw13.c hw13.h
	gcc -c $(CFLAGS) 2_hw13.c
hw13.o: hw13.c hw13.h

3_hw13.exe: 3_hw13.o hw13.o
	gcc 3_hw13.o hw13.o $(MFLAGS) -o 3_hw13.exe
3_hw13.o: 3_hw13.c hw13.h
	gcc -c $(CFLAGS) 3_hw13.c
hw13.o: hw13.c hw13.h

4_hw13.exe: 4_hw13.o hw13.o
	gcc 4_hw13.o hw13.o $(MFLAGS) -o 4_hw13.exe
4_hw13.o: 4_hw13.c hw13.h
	gcc -c $(CFLAGS) 4_hw13.c
hw13.o: hw13.c hw13.h

5_hw13.exe: 5_hw13.o hw13.o
	gcc 5_hw13.o hw13.o $(MFLAGS) -o 5_hw13.exe
5_hw13.o: 5_hw13.c hw13.h
	gcc -c $(CFLAGS) 5_hw13.c
hw13.o: hw13.c hw13.h

6_hw13.exe: 6_hw13.o hw13.o
	gcc 6_hw13.o hw13.o $(MFLAGS) -o 6_hw13.exe
6_hw13.o: 6_hw13.c hw13.h
	gcc -c $(CFLAGS) 6_hw13.c
hw13.o: hw13.c hw13.h

7_hw13.exe: 7_hw13.o hw13.o
	gcc 7_hw13.o hw13.o $(MFLAGS) -o 7_hw13.exe
7_hw13.o: 7_hw13.c hw13.h
	gcc -c $(CFLAGS) 7_hw13.c
hw13.o: hw13.c hw13.h

8_hw13.exe: 8_hw13.o hw13.o
	gcc 8_hw13.o hw13.o $(MFLAGS) -o 8_hw13.exe
8_hw13.o: 8_hw13.c hw13.h
	gcc -c $(CFLAGS) 8_hw13.c
hw13.o: hw13.c hw13.h

9_hw13.exe: 9_hw13.o hw13.o
	gcc 9_hw13.o hw13.o $(MFLAGS) -o 9_hw13.exe
9_hw13.o: 9_hw13.c hw13.h
	gcc -c $(CFLAGS) 9_hw13.c
hw13.o: hw13.c hw13.h

10_hw13.exe: 10_hw13.o hw13.o
	gcc 10_hw13.o hw13.o $(MFLAGS) -o 10_hw13.exe
10_hw13.o: 10_hw13.c hw13.h
	gcc -c $(CFLAGS) 10_hw13.c
hw13.o: hw13.c hw13.h

clean:
	rm -f hw13.o 1_hw13.o 2_hw13.o 3_hw13.o 4_hw13.o 5_hw13.o 6_hw13.o 7_hw13.o 8_hw13.o 9_hw13.o 10_hw13.o
	rm -f 1_hw13.exe 2_hw13.exe 3_hw13.exe 4_hw13.exe 5_hw13.exe 6_hw13.exe 7_hw13.exe 8_hw13.exe 9_hw13.exe 10_hw13.exe
