CFLAGS = -g
all: 1_hw12.exe 2_hw12.exe 3_hw12.exe 4_hw12.exe 5_hw12.exe 6_hw12.exe 7_hw12.exe 8_hw12.exe

1_hw12.exe: 1_hw12.o hw12.o
	gcc 1_hw12.o hw12.o -o 1_hw12.exe
1_hw12.o: 1_hw12.c hw12.h
	gcc -c $(CFLAGS) 1_hw12.c
hw12.o: hw12.c hw12.h
	gcc -c $(CFLAGS) hw12.c

2_hw12.exe: 2_hw12.o hw12.o
	gcc 2_hw12.o hw12.o -o 2_hw12.exe
2_hw12.o: 2_hw12.c hw12.h
	gcc -c $(CFLAGS) 2_hw12.c
hw12.o: hw12.c hw12.h

3_hw12.exe: 3_hw12.o hw12.o
	gcc 3_hw12.o hw12.o -o 3_hw12.exe
3_hw12.o: 3_hw12.c hw12.h
	gcc -c $(CFLAGS) 3_hw12.c
hw12.o: hw12.c hw12.h

4_hw12.exe: 4_hw12.o hw12.o
	gcc 4_hw12.o hw12.o -o 4_hw12.exe
4_hw12.o: 4_hw12.c hw12.h
	gcc -c $(CFLAGS) 4_hw12.c
hw12.o: hw12.c hw12.h

5_hw12.exe: 5_hw12.o hw12.o
	gcc 5_hw12.o hw12.o -o 5_hw12.exe
5_hw12.o: 5_hw12.c hw12.h
	gcc -c $(CFLAGS) 5_hw12.c
hw12.o: hw12.c hw12.h

6_hw12.exe: 6_hw12.o hw12.o
	gcc 6_hw12.o hw12.o -o 6_hw12.exe
6_hw12.o: 6_hw12.c hw12.h
	gcc -c $(CFLAGS) 6_hw12.c
hw12.o: hw12.c hw12.h

7_hw12.exe: 7_hw12.o hw12.o
	gcc 7_hw12.o hw12.o -o 7_hw12.exe
7_hw12.o: 7_hw12.c hw12.h
	gcc -c $(CFLAGS) 7_hw12.c
hw12.o: hw12.c hw12.h

8_hw12.exe: 8_hw12.o hw12.o
	gcc 8_hw12.o hw12.o -o 8_hw12.exe
8_hw12.o: 8_hw12.c hw12.h
	gcc -c $(CFLAGS) 8_hw12.c
hw12.o: hw12.c hw12.h

clean:
	rm -f hw12.o 1_hw12.o 2_hw12.o 3_hw12.o 4_hw12.o 5_hw12.o 6_hw12.o 7_hw12.o 8_hw12.o
	rm -f 1_hw12.exe 2_hw12.exe 3_hw12.exe 4_hw12.exe 5_hw12.exe 6_hw12.exe 7_hw12.exe 8_hw12.exe
