CFLAGS = -g
all: 1_hw10.exe 2_hw10.exe 3_hw10.exe 4_hw10.exe 5_hw10.exe 6_hw10.exe 7_hw10.exe 8_hw10.exe

1_hw10.exe: 1_hw10.o hw10.o
	gcc 1_hw10.o hw10.o -o 1_hw10.exe
1_hw10.o: 1_hw10.c hw10.h
	gcc -c $(CFLAGS) 1_hw10.c
hw10.o: hw10.c hw10.h
	gcc -c $(CFLAGS) hw10.c

2_hw10.exe: 2_hw10.o hw10.o
	gcc 2_hw10.o hw10.o -o 2_hw10.exe
2_hw10.o: 2_hw10.c hw10.h
	gcc -c $(CFLAGS) 2_hw10.c
hw10.o: hw10.c hw10.h

3_hw10.exe: 3_hw10.o hw10.o
	gcc 3_hw10.o hw10.o -o 3_hw10.exe
3_hw10.o: 3_hw10.c hw10.h
	gcc -c $(CFLAGS) 3_hw10.c
hw10.o: hw10.c hw10.h

4_hw10.exe: 4_hw10.o hw10.o
	gcc 4_hw10.o hw10.o -o 4_hw10.exe
4_hw10.o: 4_hw10.c hw10.h
	gcc -c $(CFLAGS) 4_hw10.c
hw10.o: hw10.c hw10.h

5_hw10.exe: 5_hw10.o hw10.o
	gcc 5_hw10.o hw10.o -o 5_hw10.exe
5_hw10.o: 5_hw10.c hw10.h
	gcc -c $(CFLAGS) 5_hw10.c
hw10.o: hw10.c hw10.h

6_hw10.exe: 6_hw10.o hw10.o
	gcc 6_hw10.o hw10.o -o 6_hw10.exe
6_hw10.o: 6_hw10.c hw10.h
	gcc -c $(CFLAGS) 6_hw10.c
hw10.o: hw10.c hw10.h

7_hw10.exe: 7_hw10.o hw10.o
	gcc 7_hw10.o hw10.o -o 7_hw10.exe
7_hw10.o: 7_hw10.c hw10.h
	gcc -c $(CFLAGS) 7_hw10.c
hw10.o: hw10.c hw10.h

8_hw10.exe: 8_hw10.o hw10.o
	gcc 8_hw10.o hw10.o -o 8_hw10.exe
8_hw10.o: 8_hw10.c hw10.h
	gcc -c $(CFLAGS) 8_hw10.c
hw10.o: hw10.c hw10.h



