CFLAGS = -g
all: 1_hw11.exe 2_hw11.exe 3_hw11.exe 4_hw11.exe 5_hw11.exe 6_hw11.exe 7_hw11.exe 8_hw11.exe

1_hw11.exe: 1_hw11.o hw11.o
	gcc 1_hw11.o hw11.o -o 1_hw11.exe
1_hw11.o: 1_hw11.c hw11.h
	gcc -c $(CFLAGS) 1_hw11.c
hw11.o: hw11.c hw11.h
	gcc -c $(CFLAGS) hw11.c

2_hw11.exe: 2_hw11.o hw11.o
	gcc 2_hw11.o hw11.o -o 2_hw11.exe
2_hw11.o: 2_hw11.c hw11.h
	gcc -c $(CFLAGS) 2_hw11.c
hw11.o: hw11.c hw11.h

3_hw11.exe: 3_hw11.o hw11.o
	gcc 3_hw11.o hw11.o -o 3_hw11.exe
3_hw11.o: 3_hw11.c hw11.h
	gcc -c $(CFLAGS) 3_hw11.c
hw11.o: hw11.c hw11.h

4_hw11.exe: 4_hw11.o hw11.o
	gcc 4_hw11.o hw11.o -o 4_hw11.exe
4_hw11.o: 4_hw11.c hw11.h
	gcc -c $(CFLAGS) 4_hw11.c
hw11.o: hw11.c hw11.h

5_hw11.exe: 5_hw11.o hw11.o
	gcc 5_hw11.o hw11.o -o 5_hw11.exe
5_hw11.o: 5_hw11.c hw11.h
	gcc -c $(CFLAGS) 5_hw11.c
hw11.o: hw11.c hw11.h

6_hw11.exe: 6_hw11.o hw11.o
	gcc 6_hw11.o hw11.o -o 6_hw11.exe
6_hw11.o: 6_hw11.c hw11.h
	gcc -c $(CFLAGS) 6_hw11.c
hw11.o: hw11.c hw11.h

7_hw11.exe: 7_hw11.o hw11.o
	gcc 7_hw11.o hw11.o -o 7_hw11.exe
7_hw11.o: 7_hw11.c hw11.h
	gcc -c $(CFLAGS) 7_hw11.c
hw11.o: hw11.c hw11.h

8_hw11.exe: 8_hw11.o hw11.o
	gcc 8_hw11.o hw11.o -o 8_hw11.exe
8_hw11.o: 8_hw11.c hw11.h
	gcc -c $(CFLAGS) 8_hw11.c
hw11.o: hw11.c hw11.h



